#!/bin/bash
###################################################
# Here want to delete app logs older than 7 days. #
###################################################
set -eu
LOG_DIR="/var/log/app"
DAYS=7

find "$LOG_DIR" -type f -mtime +$DAYS -exec rm -f {} \;

echo "Old logs deleted"
